name: Bug Report
description: Report a bug in the OpenTelemetry Java Examples
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in the OpenTelemetry Java Examples! 
        
        Please provide as much information as possible to help us understand and reproduce the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug you encountered.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: example
    attributes:
      label: Which example is affected?
      description: Select the example where you encountered the bug.
      options:
        - autoconfigure
        - grpc
        - http
        - jaeger
        - javaagent
        - logging
        - manual-tracing
        - metrics
        - micrometer-shim
        - otlp
        - prometheus
        - sdk-usage
        - spring-native
        - telemetry-testing
        - zipkin
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: java-version
    attributes:
      label: Java version
      description: What version of Java are you using?
      placeholder: |
        Java version:
        (Output of `java -version`)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Describe your environment
      placeholder: |
        OS: (e.g., Ubuntu 22.04, Windows 11, macOS 13.0)
        Runtime: (e.g., OpenJDK 17, Oracle JDK 21)
        Other relevant information:
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs to help explain your problem.
      placeholder: |
        Please paste relevant log output here.
        This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0