name: Feature Request
description: Suggest a new example or improvement for the OpenTelemetry Java Examples
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature or improvement for the OpenTelemetry Java Examples!
        
        Please provide as much information as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: |
        I would like to see an example that demonstrates...
        
        This example should include:
        - Feature A
        - Feature B
        - Integration with X
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: example-type
    attributes:
      label: What type of example would this be?
      description: Select the type of example you're requesting.
      options:
        - New standalone example
        - Enhancement to existing example
        - New integration example
        - Documentation improvement
        - Build/configuration improvement
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: existing-example
    attributes:
      label: If enhancing an existing example, which one?
      description: Select the example you'd like to enhance (if applicable).
      options:
        - Not applicable
        - autoconfigure
        - grpc
        - http
        - jaeger
        - javaagent
        - logging
        - manual-tracing
        - metrics
        - micrometer-shim
        - otlp
        - prometheus
        - sdk-usage
        - spring-native
        - telemetry-testing
        - zipkin
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe the use case this feature would address.
      placeholder: |
        This feature would help users who...
        
        It would be particularly useful for...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or links about the feature request here.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0